// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOOj-0XLlpUFdqdWFB6Fy2zQ75U54vRaU',
    appId: '1:452721491201:web:542a40723feff3717def00',
    messagingSenderId: '452721491201',
    projectId: 'smarthomea-43c25',
    authDomain: 'smarthomea-43c25.firebaseapp.com',
    databaseURL: 'https://smarthomea-43c25-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smarthomea-43c25.firebasestorage.app',
    measurementId: 'G-1WV22TBCPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmWfXnlIKzrgWwREJ9IKo66APOPyMZaeA',
    appId: '1:452721491201:android:8ace4ef4c550c40d7def00',
    messagingSenderId: '452721491201',
    projectId: 'smarthomea-43c25',
    databaseURL: 'https://smarthomea-43c25-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smarthomea-43c25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7C1vh0zQu590CAf-a0pO2h5Ak-nTxWY8',
    appId: '1:452721491201:ios:b795b995396c20807def00',
    messagingSenderId: '452721491201',
    projectId: 'smarthomea-43c25',
    databaseURL: 'https://smarthomea-43c25-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smarthomea-43c25.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7C1vh0zQu590CAf-a0pO2h5Ak-nTxWY8',
    appId: '1:452721491201:ios:b795b995396c20807def00',
    messagingSenderId: '452721491201',
    projectId: 'smarthomea-43c25',
    databaseURL: 'https://smarthomea-43c25-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smarthomea-43c25.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOOj-0XLlpUFdqdWFB6Fy2zQ75U54vRaU',
    appId: '1:452721491201:web:88c3a4de15babba97def00',
    messagingSenderId: '452721491201',
    projectId: 'smarthomea-43c25',
    authDomain: 'smarthomea-43c25.firebaseapp.com',
    databaseURL: 'https://smarthomea-43c25-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smarthomea-43c25.firebasestorage.app',
    measurementId: 'G-XJMRHKGQF0',
  );
}
